- name: install redis:7
  ansible.builtin.dnf:
    name: '@redis:7'
    state: present
- name: editing the ip address of  redis conf file
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: editing the protected mode of  redis conf file
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'
- name: restart the redis
  ansible.builtin.systemd_service:
    name: redis
    enabled: true
    state: restarted