- name: install golang
  ansible.builtin.dnf:
    name: golang
    state: present

- name: load app_pre_reqs
  ansible.builtin.import_role:
    name: common
    tasks_from: app_pre_reqs.yml

- name: init, get, build
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

- name: load app_pre_reqs
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd.yml