- name: Install Maven
  ansible.builtin.dnf:
    name: 'maven'
    state: present

- name: load app_pre_reqs
  ansible.builtin.import_tasks: app_pre_reqs.yml

- name: Install maven dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{ component }}-1.0.jar {{ component }}.jar
  args:
    chdir: /app/

- name: import systemd tasks
  ansible.builtin.import_tasks: systemd.yml