- name: install nodejs:20
  ansible.builtin.dnf:
    name: '@nodejs:20'
    state: present

- name: load app_pre_reqs
  ansible.builtin.import_tasks: app_pre_reqs.yml

- name: install packages
  community.general.npm:
    path: /app

- name: import systemd tasks
  ansible.builtin.import_tasks: systemd.yml